# Generated by Django 2.0.13 on 2020-08-24 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20200824_2202'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='reigstered_dttm',
            new_name='registered_dttm',
        ),
    ]
