# Generated by Django 2.0.13 on 2020-08-24 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_auto_20200824_2214'),
    ]

    operations = [
        migrations.RenameField(
            model_name='board',
            old_name='reigstered_dttm',
            new_name='registered_dttm',
        ),
        migrations.AlterField(
            model_name='board',
            name='writer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.User', verbose_name='작성자'),
        ),
    ]
